/*
* generated by Xtext
*/
package eu.metatools.technocat.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TechnoCatAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("eu/metatools/technocat/parser/antlr/internal/InternalTechnoCat.tokens");
	}
}
