/*
* generated by Xtext
*/
package eu.metatools.technocat.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import eu.metatools.technocat.services.TechnoCatGrammarAccess;

public class TechnoCatParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TechnoCatGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_SL_COMMENT");
	}
	
	@Override
	protected eu.metatools.technocat.parser.antlr.internal.InternalTechnoCatParser createParser(XtextTokenStream stream) {
		return new eu.metatools.technocat.parser.antlr.internal.InternalTechnoCatParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "TechnologyCatalog";
	}
	
	public TechnoCatGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TechnoCatGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
