/*
 * generated by Xtext
 */
package eu.metatools.technocat.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractTechnoCatValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(eu.metatools.technocat.technoCat.TechnoCatPackage.eINSTANCE);
		return result;
	}
}
