/*
 * generated by Xtext
 */
package eu.metatools.technocat.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider;

import com.google.inject.Binder;

import eu.metatools.technocat.ui.hover.TechnoCatHoverProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TechnoCatUiModule extends AbstractTechnoCatUiModule
{
	public TechnoCatUiModule(AbstractUIPlugin plugin)
	{
		super(plugin);
	}

	@Override
	public void configure(Binder binder)
	{
		super.configure(binder);

		binder.bind(IEObjectHoverProvider.class).to(TechnoCatHoverProvider.class);
	}
}
