/*
 * generated by Xtext
 */
package eu.metatools.technocat;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class TechnoCatRuntimeModule extends AbstractTechnoCatRuntimeModule
{
}
