/*
* generated by Xtext
*/
package eu.metatools.technocat;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TechnoCatStandaloneSetup extends TechnoCatStandaloneSetupGenerated{

	public static void doSetup() {
		new TechnoCatStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

