/*
* generated by Xtext
*/
package eu.metatools.technocat;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class TechnoCatUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return eu.metatools.technocat.ui.internal.TechnoCatActivator.getInstance().getInjector("eu.metatools.technocat.TechnoCat");
	}
	
}
