/*
 * generated by Xtext
 */
package eu.metatools.technocat.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import eu.metatools.technocat.ui.internal.TechnoCatActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TechnoCatExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TechnoCatActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TechnoCatActivator.getInstance().getInjector(TechnoCatActivator.EU_METATOOLS_TECHNOCAT_TECHNOCAT);
	}
	
}
