/*
 * generated by Xtext
 */
package eu.metatools.technocat.ui.contentassist

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class TechnoCatProposalProvider extends AbstractTechnoCatProposalProvider {
}
